### PR TITLE
Fix XCode 4.6 warnings on ->isA

### PR DESCRIPTION
**Pull request by SpacyRicochet**

### CODE REVIEW

**Comment by stanislaw** [comment]
+1 for this. The same for #106, #107, #116, #117, #118, #119, #120

**Comment by grzegorzkrukowski** [comment]
+1 for this

**Comment by lmcgs** [comment]
+1 for this

**Comment by Orion98MC** [comment]
+1 for this

**Comment by ghost** [comment]
+1 for this

**Comment by wyattw** [comment]
+1 for this

**Comment by raycartalla** [comment]
+1 for this

**Comment by johnz2** [comment]
+1

**Comment by willlarche** [comment]
+1

**Comment by stephanheilner** [comment]
+1, won't even compile with Xcode 5 without this

**Comment by drn** [comment]
+1 can we merge this?

**Comment by rayh** [comment]
+1

**Comment by olivierkaisin** [comment]
+1

**Comment by tasomaniac** [comment]
+1

**Comment by awesomejue** [comment]
+1

------------------ 原始邮件 ------------------
发件人: "Said Tahsin Dane"; 
发送时间: 2014年1月21日(星期二) 晚上6:52
收件人: "johnezang/JSONKit";
主题: Re: [JSONKit] Fix XCode 4.6 warnings on ->isA (#121)

+1

&mdash;

**Comment by breath103** [comment]
+1

**Comment by thatguydan** [comment]
+1

**Comment by SpacyRicochet** [comment]
Closing this, since it's been **[cough]** a while.

**Pull request closed without merging**
