### PR TITLE
use `object_setClass()` instead of deprecated `isa`

### PR DESCRIPTION
**Pull request by dhilipsiva**

### CODE REVIEW

**Comment by dhilipsiva** [comment]
Sorry, My bad. I didn't check the last pull request. This is already done there. Closing.

**Comment by akinLiu** [comment]
but the worning still there

**Comment by dhilipsiva** [comment]
@akinLiu It shouldn't be throwing this warning. Are you sure your copy of JSONKit is updated?

**Comment by akinLiu** [comment]
@dhilipsiva I use pod, this is my pod config: `pod 'JSONKit',   '1.5pre'`,there is still worning!

**Comment by dhilipsiva** [comment]
@akinLiu Looks like 1.5pre ( https://github.com/CocoaPods/Specs/blob/master/JSONKit/1.5pre/JSONKit.podspec#L8 ) is pointing to the commit 0aff3deb5e1bb2bbc88a83fd71c8ad5550185cce which clearly doesn't include ( https://github.com/johnezang/JSONKit/compare/0aff3deb5e1bb2bbc88a83fd71c8ad5550185cce...master#L0L2791 ) this fix. So try pulling the latest code from GitHub manually or update the Specs repo of Cocoapods to point to the latest.

**Pull request closed without merging**
